backend/models/User.php
<?php

namespace backend\models;

use Yii;
use yii\helpers\VarDumper;

/**
 * This is the model class for table "user".
 *
 * @property integer $id
 * @property string $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property integer $status
 * @property integer $role
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property Address[] $addresses
 * @property Cart[] $carts
 * @property CartProduct[] $cartProducts
 * @property Loyality[] $loyalities
 * @property Order[] $orders
 * @property Profile[] $profiles
 */
class User extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */

    public $password;
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['email', 'role','password','firstname','lastname','status'], 'required'],
            [['status', 'role', 'created_at', 'updated_at'], 'integer'],
            [['username', 'password_hash', 'password_reset_token', 'email'], 'string', 'max' => 255],
            [['auth_key','firstname','lastname'], 'string', 'max' => 32],
            [['username'], 'unique'],
            [['email'], 'unique'],
            [['password_reset_token'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => Yii::t('backend','username'),
            'firstname' => Yii::t('backend','firstname'),
            'lastname' => Yii::t('backend','lastname'),
            'auth_key' => 'Auth Key',
            'password_hash' => 'Password Hash',
            'password' =>  Yii::t('backend','password'),
            'password_reset_token' => 'Password Reset Token',
            'email' => Yii::t('backend','email'),
            'status' => Yii::t('backend','status'),
            'role' => Yii::t('backend','role'),
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAddresses()
    {
        return $this->hasMany(Address::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarts()
    {
        return $this->hasMany(Cart::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCartProducts()
    {
        return $this->hasMany(CartProduct::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoyalities()
    {
        return $this->hasMany(Loyality::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrders()
    {
        return $this->hasMany(Order::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProfiles()
    {
        return $this->hasMany(Profile::className(), ['user_id' => 'id']);
    }

    public function saveUser(){
        $userArray = Yii::$app->request->post('User');
        $validateUser = User::find()->where(['email'=>$userArray['email']])->one();
        if(empty($validateUser)){
            $this->firstname = $userArray['firstname'];
            $this->lastname = $userArray['lastname'];
            $this->username = $userArray['firstname'].' '.$userArray['lastname'];
            $this->email = $userArray['email'];
            $this->password_hash = Yii::$app->security->generatePasswordHash($userArray['password']);
            $this->status = $userArray['status'];
            $this->role = $userArray['role'];
            $this->save();
            Yii::$app->controller->redirect('/admin/user/index');
        }else{
            Yii::$app->session->setFlash('emailError','This email is not available');
            Yii::$app->controller->redirect(Yii::$app->request->url);
        }

    }

    public function getFullname(){
        return $this->firstname.' '.$this->lastname;
    }
}

common/models/Rating.php
<?php

namespace common\models;

use backend\models\User;

use Yii;
use yii\helpers\Html;
use yii\helpers\Json;
use yii\helpers\VarDumper;


/**
 * This is the model class for table "profile".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $
 *
 * @property User $user
 */
class Rating extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */

    public static function tableName()
    {
        return 'rating';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id','rating'], 'integer'],
            [['user_id'], 'required'],
            [['status','comment','token'], 'string'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User',
            'rating' => 'Rating',
            'comment' => 'Comment',
        ];
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getMine()
    {
        if(!yii::$app->user->isGuest && (yii::$app->user->id==$this->user_id)){
            return true;
        } return false;
    }

}

backend/controllers/RatingController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Rating;
use backend\models\RatingSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RatingController implements the CRUD actions for Rating model.
 */
class RatingController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Rating models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RatingSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Rating model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Rating model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Rating();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Rating model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Rating model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Rating model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Rating the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Rating::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/RatingController.php
<?php
/**
 * Created by PhpStorm.
 * User: fuad
 * Date: 1/18/16
 * Time: 3:27 PM
 */

namespace frontend\controllers;


use common\models\Rating;
use frontend\models\Category;
use frontend\models\CategoryLang;
use frontend\models\Manufacturer;
use frontend\models\Product;
use yii\helpers\VarDumper;
use yii\web\Controller;
use Yii;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;


class RatingController extends Controller
{

//    public function behaviors()
//    {
//        return [
//            'access' => [
//                'class' => AccessControl::className(),
//                'only' => ['index'],
//                'rules' => [
//                    [
//                        'actions' => ['index'],
//                        'allow' => true,
//                        'roles' => ['@'],
//                    ],
//                ],
//            ],
//        ];
//    }

    public function actionIndex(){
        $model = Rating::find()->where(['status'=>'1'])->all();

        return $this->render('index',
            ['ratings'=>$model]);
    }

    public function actionRate($token){
        $model = Rating::find()->where(['token'=>$token])->one();
        if($model) {
            if(Yii::$app->request->get() && Yii::$app->request->isAjax){
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                $rating_status = '0';
                if(isset($_GET['Rating'])){
                    $rating_point = intval(yii::$app->request->get('Rating',0)['rating']);
                    $comment = yii::$app->request->get('Rating',"")['comment'];
                } else{
                    if(isset($_GET['comment'])) {
                        $comment = yii::$app->request->get('comment');
                    } else {
                        $comment = $model->comment;
                    }
                    if(isset($_GET['rating'])) {
                        $rating_point = intval(yii::$app->request->get('rating',0));
                        $rating_status = '1';
                    }else {
                        $rating_point = $model->rating;
                    }
                }

                $model->rating = $rating_point;
                $model->comment = $comment;
                $model->status = $rating_status;
                $model->save();
                if($rating_point==0) {
                    return [
                        'message'=>'Please select your rating.',
                        'created'=>0
                    ];
                } else {
                    return [
                        'message'=>'Rated successfully.',
                        'created'=>1,
                        'approveText'=>'Your rate will be published after approved by admin.'
                    ];
                }

            }
            return $this->render('rate',
                ['model'=>$model]);
        } else {
            throw new ForbiddenHttpException;
        }

    }


    public function actionManufacturersImage(){
        $connection = Yii::$app->getDb();
        $command = $connection->createCommand("SELECT DISTINCT(category_lang.name),category_lang.category_id FROM `category` left join `category_lang` on category.id=category_lang.category_id where nleft+1=nright and category_lang.language='ru'");
        $result = $command->queryAll();
        $count = 0;
        $without_img = 0;
        $after_img = 0;
        foreach($result as $r){
            $count++;
            //add manufacturer
            $m = new Manufacturer();
            $m->id = $r['category_id'];
            $m->name = $r['name'];
            $m->image = $r['category_id'].'.jpg';
            $m->status = '1';
            $m->deleted = 0;
            $m->save();

            $category = Category::find()->where(['id'=>$r['category_id']])->one();
            //update product which category_id is manufacturer id, set manufacturer id.
            Product::updateAll(['category_id'=>$category->parent_id,'manufacturer_id'=>$category->id],['category_id'=>$r['category_id']]);

            //delete category which removed to manufacturer
            CategoryLang::deleteAll(['category_id'=>$r['category_id']]);
            $category->delete();

            //move image from last category to manufacturer
            if(file_exists(yii::getAlias('@frontend/web/uploads/categories/'.$m->image))){
                copy(yii::getAlias('@frontend/web/uploads/categories/'.$m->image),yii::getAlias('@frontend/web/uploads/manufacturer/'.$m->image));
            } else {
                $without_img++;
                //if image don't exist find image from with same name categories(if exist)
               $_categories = CategoryLang::find()->where(['name'=>$m->name])->all();
                foreach($_categories as $cat) {
                    $_img = $cat->id.'.jpg';
                    if(file_exists(yii::getAlias('@frontend/web/uploads/categories/'.$_img))){
                        $after_img++;
                        copy(yii::getAlias('@frontend/web/uploads/categories/'.$_img),yii::getAlias('@frontend/web/uploads/manufacturer/'.$m->image));
                        break;
                    }
                }
            }

            if(!file_exists(yii::getAlias('@frontend/web/uploads/manufacturer/'.$m->image))){
                echo $m->image."<br/>";
            }
        }

        //statistics
        echo "<br/> count:".$count;
        echo "<br/> without image:".$without_img."<br>";
        echo "after image:".$after_img."<br>";
        echo "with image1:".(intval($count)-intval($without_img))."<br>";
        echo "with image2:".(intval($count)-intval($without_img)+intval($after_img))."<br>";

    }

}

frontend/views/rating/index.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use kartik\rating\StarRating;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Ratings';
$this->params['breadcrumbs'][] = $this->title;
?>

    <div class="" style="text-align: center;">
    <div class="rating-list">
        <?php if($ratings):?>
        <?php foreach($ratings as $rating):?>
            <div class="rating-item">
                <?php
                echo StarRating::widget([
                    'name' => 'Rating[rating]',
                    'value'=>$rating->rating,
                    'disabled'=>!$rating->mine,
                    'pluginOptions' => [
                        'min' => 0,
                        'max' => 5,
                        'step' => 1,
                        'size' => 'md',
                    ],
                    'pluginEvents'=>[
                        'rating.change'=>"function(){
                            var _this = $(this);
                            var item = _this.parents('.rating-item');
                            var token = $('.rating-item > i.fa').data('token');
                            var rating = $(this).val();

                            $.ajax({
                                url: '/rating/rate?token=' + token,
                                dataType: 'json',
                                type: 'get',
                                data: {'rating':rating},
                                success: function (data) {
                                    if (data.created == 1) {

                                    }
                                },
                                error: function (data) {
                                    //
                                }
                            });

                        }"
                    ]
                ]);?>
                <?php if($rating->mine):?>
                    <i data-token="<?=$rating->token?>" class="fa fa-2x fa-pencil-square-o"></i>
                <?php endif;?>
                <div class="user"><?=$rating->user->fullname?></div>
                <span class="review-comment">
                    <?=$rating->comment?>
                </span>
            </div>
        <?php endforeach;?>
        <?php else:?>
            <div class="alert alert-info">There is no any rating yet.
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button></div>
        <?php endif;?>

    </div>
    </div>

<div id="ratingEditModal" class='modal fade' role='dialog'> <div class='modal-dialog'></div>

frontend/views/rating/rate.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use kartik\rating\StarRating;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Rate';
$this->params['breadcrumbs'][] = $this->title;
?>

    <div class="col-lg-60">
    <div class="rate-order">
        <?php $form = ActiveForm::begin(['id' => 'rate-order-form']); ?>

        <?php // Control the number of stars, each caption value, and styles for display
        echo StarRating::widget([
            'name' => 'Rating[rating]',
            'pluginOptions' => [
                'min' => 0,
                'max' => 5,
                'step' => 1,
                'size' => 'sm',
                'required'=>true,
                'starCaptions' => [
                    1 => 'Very Poor',
                    2 => 'Poor',
                    3 => 'Ok',
                    4 => 'Good',
                    5 => 'Very Good',
                ],
                'starCaptionClasses' => [
                    1 => 'text-danger',
                    2 => 'text-warning',
                    3 => 'text-info',
                    4 => 'text-primary',
                    5 => 'text-success',
                ],
            ],
        ]);?>

        <textarea class="rating-comment" rows="4" required="required" name="Rating[comment]"></textarea>

        <div class="form-group">
            <button data-token="<?=$model->token?>" type="button" class="btn btn-primary">Rate</button>
        </div>


        <?php ActiveForm::end(); ?>

    </div>
    </div>